//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by text2prn.rc
//
#define IDD_MAIN                        101
#define IDI_MAIN                        102
#define IDD_INFO                        103
#define IDD_EDIT_PRESET                 104
#define IDD_PREVIEW_BAR                 105
#define IDD_FILE_LIST                   106
#define IDR_FILE_LIST                   107
#define IDD_ENCODING                    108
#define IDD_CONFIRM_NAME                109
#define IDD_TEXT                        120
#define IDD_FONT                        121
#define IDD_REGION                      122
#define IDD_SPACE                       123
#define IDD_HEADER                      124
#define IDD_OPTION                      125
#define IDD_PREVIEW                     126
#define IDC_TAB                         1000
#define IDC_FROM_FILE                   1001
#define IDC_FROM_MULTI_FILE             1002
#define IDC_FROM_CLIP                   1003
#define IDC_FILE                        1004
#define IDC_REF                         1005
#define IDC_REF_MULTI                   1006
#define IDC_ENCODING                    1007
#define IDC_CHAR                        1020
#define IDC_LINE                        1021
#define IDC_FONT                        1022
#define IDC_COLUMN                      1023
#define IDC_TABNUM                      1024
#define IDC_CHAR1                       1025
#define IDC_LINE1                       1026
#define IDC_FONT1                       1027
#define IDC_CHAR2                       1028
#define IDC_LINE2                       1029
#define IDC_FONT2                       1030
#define IDC_WRAP_RIGHT                  1031
#define IDC_FONT_TYPE                   1040
#define IDC_FONT_NAME                   1041
#define IDC_VERTICAL                    1042
#define IDC_PROPORTIONAL                1043
#define IDC_FIRST                       1060
#define IDC_BEGIN1                      1061
#define IDC_LAST                        1062
#define IDC_END_L1                      1063
#define IDC_TO_L1                       1064
#define IDC_END_P1                      1065
#define IDC_BEGIN                       1066
#define IDC_END_LINE                    1067
#define IDC_TO_LINE                     1068
#define IDC_END_PAGE                    1069
#define IDC_BEGIN2                      1070
#define IDC_END_L2                      1071
#define IDC_TO_L2                       1072
#define IDC_END_P2                      1073
#define IDC_USE_SPACE                   1080
#define IDC_TOP                         1081
#define IDC_BOTTOM                      1082
#define IDC_LEFT                        1083
#define IDC_RIGHT                       1084
#define IDC_STOP                        1085
#define IDC_SBOTTOM                     1086
#define IDC_SLEFT                       1087
#define IDC_SRIGHT                      1088
#define IDC_LINE_SPACE                  1089
#define IDC_COLUMN_SPACE                1090
#define IDC_SCOLUMN                     1091
#define IDC_VIEWINFO                    1100
#define IDC_VIEWLINE                    1101
#define IDC_LINE_DIGIT                  1102
#define IDC_COLUMN_LINE                 1103
#define IDC_VIEWPAGE                    1104
#define IDC_VIEWTITLE                   1105
#define IDC_PRESET                      1106
#define IDC_PRESET_APPLY                1107
#define IDC_PRESET_EDIT                 1108
#define IDC_PREVIEW                     1120
#define IDC_PAGE_SETUP                  1121
#define IDC_ATTRIBUTE_LIST              1140
#define IDC_PROPERTY                    1160
#define IDC_NAME                        1161
#define IDC_PRESET_LIST                 1162
#define IDC_ADD                         1163
#define IDC_DEL                         1164
#define IDC_NEXTPAGE                    1180
#define IDC_PREVPAGE                    1181
#define IDC_PAGE                        1182
#define IDC_ZOOM                        1183
#define IDC_CLOSE                       1184
#define IDC_FILE_LIST                   1200
#define IDC_NEW_LINE                    1201
#define IDC_NEW_COLUMN                  1202
#define IDC_NEW_PAGE                    1203
#define IDC_LINE_COUNT                  1204
#define IDC_UP                          1205
#define IDC_DOWN                        1206
#define IDC_APPEND                      1220
#define IDC_OVERWRITE                   1221
#define IDC_IMAGE                       1223
#define IDC_USE_HEADER                  1240
#define IDC_HEAD_L                      1241
#define IDC_HEAD_C                      1242
#define IDC_HEAD_R                      1243
#define IDC_FOOT_L                      1244
#define IDC_FOOT_C                      1245
#define IDC_FOOT_R                      1246
#define ID_ADD_FILE                     40001
#define ID_DEL_FILE                     40002
#define ID_CLEAR_FILE_LIST              40003
#define ID_MOVE_UP                      40004
#define ID_MOVE_DOWN                    40005
#define ID_ENCODING                     40006
#define ID_SELECT_ALL                   40007
#define ID_SELECT_INVERT                40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1260
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
